# Form implementation generated from reading ui file 'gui_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fioEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fioEdit.setGeometry(QtCore.QRect(100, 20, 351, 20))
        self.fioEdit.setObjectName("fioEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.approveButton = QtWidgets.QPushButton(self.centralwidget)
        self.approveButton.setGeometry(QtCore.QRect(480, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.approveButton.setFont(font)
        self.approveButton.setObjectName("approveButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.votingInfoWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.votingInfoWidget.setGeometry(QtCore.QRect(60, 100, 291, 192))
        self.votingInfoWidget.setObjectName("votingInfoWidget")
        self.votingInfoWidget.setColumnCount(2)
        self.votingInfoWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.votingInfoWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.votingInfoWidget.setHorizontalHeaderItem(1, item)
        self.createDESButton = QtWidgets.QPushButton(self.centralwidget)
        self.createDESButton.setGeometry(QtCore.QRect(480, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createDESButton.setFont(font)
        self.createDESButton.setObjectName("createDESButton")
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setGeometry(QtCore.QRect(434, 170, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.questionLabel.setFont(font)
        self.questionLabel.setObjectName("questionLabel")
        self.yesBox = QtWidgets.QCheckBox(self.centralwidget)
        self.yesBox.setGeometry(QtCore.QRect(430, 210, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.yesBox.setFont(font)
        self.yesBox.setObjectName("yesBox")
        self.noBox = QtWidgets.QCheckBox(self.centralwidget)
        self.noBox.setGeometry(QtCore.QRect(430, 240, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.noBox.setFont(font)
        self.noBox.setObjectName("noBox")
        self.wantVoteButton = QtWidgets.QPushButton(self.centralwidget)
        self.wantVoteButton.setGeometry(QtCore.QRect(55, 316, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wantVoteButton.setFont(font)
        self.wantVoteButton.setObjectName("wantVoteButton")
        self.voteButton = QtWidgets.QPushButton(self.centralwidget)
        self.voteButton.setGeometry(QtCore.QRect(430, 270, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.voteButton.setFont(font)
        self.voteButton.setObjectName("voteButton")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(40, 490, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(430, 380, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ####################################
        #           user code
        ####################################

        self.fio = ""

        self.approveButton.clicked.connect(self.get_fio)
        self.updateButton.clicked.connect(self.update_info)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Твое ФИО"))
        self.approveButton.setText(_translate("MainWindow", "Подтвердить"))
        self.label_2.setText(_translate("MainWindow", "Участники голосования"))
        item = self.votingInfoWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "приглашенные"))
        item = self.votingInfoWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "подтвержденные"))
        self.createDESButton.setText(_translate("MainWindow", "Создать Ключи ЭЦП"))
        self.questionLabel.setText(_translate("MainWindow", "Вопрос голосования"))
        self.yesBox.setText(_translate("MainWindow", " Да (манда)"))
        self.noBox.setText(_translate("MainWindow", " Нет (пидора ответ)"))
        self.wantVoteButton.setText(_translate("MainWindow", "Хочу участвовать!"))
        self.voteButton.setText(_translate("MainWindow", "Press F to Vote"))
        self.updateButton.setText(_translate("MainWindow", "Обновить информацию"))
        self.resultLabel.setText(_translate("MainWindow", "Победил ответ...."))


    def get_fio(self):
        self.fio = self.fioEdit.text().lower();
        print(self.fio)


    def update_info(self):
        pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
